[window]
startup_mode="Maximized"

[font]
size = 10

[font.normal]
family = "Hurmit Nerd Font Mono"
style = "Regular"

[terminal]
shell = "/bin/zsh"

[general]
import = ["/home/wonebone/.config/alacritty/themes/themes/flexoki.toml"]
