[window]
startup_mode="Maximized"
opacity=0.90

[font]
size = 8

[font.normal]
family = "Hurmit Nerd Font Mono"
style = "Regular"

[terminal]
shell = "/bin/zsh"

[general]
import = ["/home/wonebone/.config/alacritty/themes/themes/flexoki.toml"]
